w10d01/lotr/config/routes.rb
Rails.application.routes.draw do
  resources :enemies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # post 'login', to: 'users#create'
  # post 'login', action: :create, controller: 'users'

  # resources :locations, except: [:show, :create]
  # resources :locations

  # resources :characters

  resources :locations do
    resources :characters
  end
end

w10d01/lotr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/lotr/app/models/cactu.rb
class Cactu < ApplicationRecord
end

w10d01/lotr/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :location
end

w10d01/lotr/app/models/city.rb
class City < ApplicationRecord
end

w10d01/lotr/app/models/dice.rb
class Dice < ApplicationRecord
end

w10d01/lotr/app/models/enemy.rb
class Enemy < ApplicationRecord
end

w10d01/lotr/app/models/location.rb
class Location < ApplicationRecord
  has_many :characters
end

w10d01/lotr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/lotr/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @location = Location.find params[:location_id]

    @characters = @location.characters
  end
end

w10d01/lotr/app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy, only: %i[ show edit update destroy ]

  # GET /enemies or /enemies.json
  def index
    @enemies = Enemy.all
  end

  # GET /enemies/1 or /enemies/1.json
  def show
  end

  # GET /enemies/new
  def new
    @enemy = Enemy.new
  end

  # GET /enemies/1/edit
  def edit
  end

  # POST /enemies or /enemies.json
  def create
    @enemy = Enemy.new(enemy_params)

    respond_to do |format|
      if @enemy.save
        format.html { redirect_to enemy_url(@enemy), notice: "Enemy was successfully created." }
        format.json { render :show, status: :created, location: @enemy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enemy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enemies/1 or /enemies/1.json
  def update
    respond_to do |format|
      if @enemy.update(enemy_params)
        format.html { redirect_to enemy_url(@enemy), notice: "Enemy was successfully updated." }
        format.json { render :show, status: :ok, location: @enemy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enemy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enemies/1 or /enemies/1.json
  def destroy
    @enemy.destroy

    respond_to do |format|
      format.html { redirect_to enemies_url, notice: "Enemy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enemy
      @enemy = Enemy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enemy_params
      params.fetch(:enemy, {})
    end
end

w10d01/lotr/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
end

w10d01/lotr/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/lotr/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/lotr/app/helpers/enemies_helper.rb
module EnemiesHelper
end

w10d01/lotr/app/helpers/locations_helper.rb
module LocationsHelper
end

w10d01/lotr/app/views/characters/_character.html.erb
<div class="character">
  <h2>Name: <%= character.name %></h2>
  <h2>Poem: <%= character.poem %></h2>
  <h2>Race: <%= character.race %></h2>
  <h2>Location: <%= character.location.name %></h2>
</div>

w10d01/lotr/app/views/characters/index.html.erb
<h1>All the characters for <%= @location.name %></h1>

<%= link_to "See all the locations", locations_path %>

<!-- <% @characters.each do |character| %>
  <%= render 'character', character: character %>
<% end %> -->

<%= render @characters %>

w10d01/lotr/app/views/enemies/_form.html.erb
<%= form_with(model: enemy) do |form| %>
  <% if enemy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enemy.errors.count, "error") %> prohibited this enemy from being saved:</h2>

      <ul>
        <% enemy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/lotr/app/views/enemies/edit.html.erb
<h1>Editing Enemy</h1>

<%= render 'form', enemy: @enemy %>

<%= link_to 'Show', @enemy %> |
<%= link_to 'Back', enemies_path %>

w10d01/lotr/app/views/enemies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enemies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enemies.each do |enemy| %>
      <tr>
        <td><%= link_to 'Show', enemy %></td>
        <td><%= link_to 'Edit', edit_enemy_path(enemy) %></td>
        <td><%= link_to 'Destroy', enemy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enemy', new_enemy_path %>

w10d01/lotr/app/views/enemies/new.html.erb
<h1>New Enemy</h1>

<%= render 'form', enemy: @enemy %>

<%= link_to 'Back', enemies_path %>

w10d01/lotr/app/views/enemies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enemy_path(@enemy) %> |
<%= link_to 'Back', enemies_path %>

w10d01/lotr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/lotr/app/views/locations/index.html.erb
<h1>All the locations!</h1>

<% @locations.each do |location| %>
  <div class="location">
    <h2>Name: <%= location.name %></h2>
    <%= link_to "Visit the characters page", location_characters_path(location) %>
  </div>
<% end %>